apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: terraform-plan

on:
  push:
    branches:
      - "**"
  workflow_dispatch: {}

jobs:
  build:
    steps:
      - name: Configure AWS credentials
        id: configureAwsCredentials
        uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
